[package]
name = "arenas"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }

[lib]
name = "arenas"
path = "src/lib/mod.rs"

[[bin]]
name = "arenas"
